config/routes.rb
Rails.application.routes.draw do
  mount MissionControl::Jobs::Engine, at: "/jobs"

  root 'spaces#index'

  namespace :searches do
    resources :users, only: [:index]
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :spaces, only: [:index, :show, :new, :create, :edit, :update, :destroy] do 
    member do 
      post :toggle_occupied
      post :toggle_status_active
      post :toggle_status_disable
      get :reservation_history
    end

    collection do
      get :reservation_history_filter
    end
  end
  
  resources :reservations, only: [:new, :create, :edit, :update, :destroy] do 
    collection do
      get :pending_reservation
    end
    member do 
      get :justification_approve
      patch :approve

      get :justification_cancel
      patch :cancel
    end
  end
end

app/models/space.rb
class Space < ApplicationRecord
  has_many :reservations, dependent: :destroy 

  enum floor: { ground: 0, first_floor: 1, second_floor: 2 }

  validates :name, presence: true 
  validates :location, presence: true 
  validates :capacity, presence: true

  # Atributos que podem ser pesquisados
  def self.ransackable_attributes(auth_object = nil)
    ["board", "capacity", "id", "id_value", "laboratory", "location", "name", "projector", "floor", "accessibility"]
  end

  # Permitir busca através da associação 'reservations'
  def self.ransackable_associations(auth_object = nil)
    ["reservations"]
  end
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  before_action :set_space, only: %i[show edit update destroy toggle_occupied toggle_status_active toggle_status_disable reservation_history]
  before_action :start_date, only: %i[show]
  before_action :set_action, only: %i[edit update]
  before_action :authorize_space, only: %i[show]

  def index
    @q = Space.ransack(params[:q]) # Busca pelo Ransack
    @any_spaces_exist = Space.exists?
    
    @spaces = @q.result.order(:name)
    # current_user.admin? ? @spaces = @q.result.order(:name) : @spaces = @q.result.where(active: true).order(:name) 
  end

  def show
    session[:last_space_id] = @space.id

    if params[:my_reservations].present?
      session[:my_reservations] = params[:my_reservations] == '1'
    end

    @my_reservations = session[:my_reservations]
    
    if @my_reservations
      @reservations = @space.reservations.where(user_id: current_user.id, start_date: start_date.beginning_of_month.beginning_of_week..start_date.end_of_month.end_of_week)
    else 
      @reservations = @space.reservations.where(start_date: start_date.beginning_of_month.beginning_of_week..start_date.end_of_month.end_of_week)
    end
  end

  def reservation_history
    start_date = params[:start_date]
    end_date = params[:end_date]

    if start_date.present? && end_date.present?
      @reservations_history = @space.reservations.by_date_range(start_date, end_date).order(:start_date)
    else
      @reservations_history = @space.reservations.all.order(:start_date)
    end

    respond_to do |format|
      format.html { redirect_to space_path(@space.id) }
      format.pdf do
        render pdf: 'histórico-reservas',
              template: 'spaces/reservation_history',
              # disposition: 'attachment',                  # default 'inline'
              page_size: 'A4'
      end
    end
  end

  def reservation_history_filter
    @q = Space.ransack(params[:q])
    start_date = params[:start_date]
    end_date = params[:end_date]

    if start_date.present? && end_date.present? || @q.present?
      space_ids = @q.result.pluck(:id) # Pega os IDs dos espaços
      @reservations_history_filter = Reservation.where(space_id: space_ids)
                                                .by_date_range(start_date, end_date)
                                                .order(:start_date)
    end

    respond_to do |format|
      format.html { redirect_to spaces_path }
      format.pdf do
        render pdf: 'histórico-reservas',
              template: 'spaces/reservation_history_filter',
              # disposition: 'attachment',                  # default 'inline'
              page_size: 'A4'
      end
    end
  end

  def new
    @space = Space.new
    authorize @space
  end 

  def create 
    @space = Space.new(space_params)
    authorize @space

    if @space.save 
      flash[:notice] = 'Espaço cadastrado com sucesso!'
      redirect_to spaces_path
    else
      respond_to do |format|
        format.turbo_stream
      end
    end
  end

  def edit; end 

  def update  
    authorize @space

    if @space.update(space_params)
      flash[:notice] = 'Espaço atualizado com sucesso!'
      redirect_to spaces_path
    else
      respond_to do |format|
        format.turbo_stream
      end
    end
  end

  def destroy 
    authorize @space
    @space.destroy
    flash[:notice] = 'Espaço excluído com sucesso!'
    redirect_to spaces_path
  end

  def toggle_occupied
    @space.update!(occupied: !@space.occupied)
  end

  def toggle_status_active
    @space.update!(active: true, disabled_reason: nil)
  end

  # def disabled_reason; end
  
  def toggle_status_disable   
    disable_reason = params[:disable_reason]

    if @space.update!(active: false, disabled_reason: disable_reason)
      flash[:notice] = "Espaço desabilitado com sucesso."
      redirect_to spaces_path
    else
      flash.now[:alert] = "Não foi possível disabilitar o espaço."
    end
  end

  private
    def space_params
      params.require(:space).permit(:name, :description, :board, :laboratory, :projector, :accessibility, :location, :capacity, :floor, :disabled_reason)
    end

    def set_space
      @space = Space.find(params[:id])
    end

    def start_date
      params.fetch(:start_date, Date.today).to_date
    end

    def set_action
      @action = 'edit'
    end

    def authorize_space 
      if (@space.occupied? || !@space.active?) && !current_user.admin?
        flash[:alert] = "O espaço está ocupado ou desabilitado e você não tem permissão para acessá-lo!"
        redirect_to spaces_path
      end
    end
end

app/helpers/spaces_helper.rb
module SpacesHelper
end

app/views/spaces/_calendar.html.erb
<div class="calendar-container" data-controller="calendar">
  <%= month_calendar(events: @reservations) do |date, reservations| %>
    <div class="day" data-date="<%= date %>" data-calendar-target="day">
      <%= date.day %>

      <% reservations.each do |reservation| %>
        <% reservation.shifts.each do |item| %>
          <% if reservation.shifts.present? %>
              <%= link_to edit_reservation_path(reservation), data: { turbo_frame: "modal" }, class: "link-to" do %>
                <div class="reservation-shift-<%= item %> <%= 'pending' if reservation.status == 'pending' %>">
                  <%= I18n.t("activerecord.attributes.reservation.shifts.#{item}") %>  
                </div>
              <% end %>  
          <% end %>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/spaces/_disable_reason_form.html.erb
<%= form_with url: toggle_status_disable_space_path(space), id: "disable_reason_form" do |f| %>
  <%= f.label :disable_reason, "Justificativa para desabilitar" %>
  <%= error_messages_for_field(space, :disable_reason) %>
  <%= f.text_area :disable_reason, rows: 4, id: "rejection-reason", placeholder: "Digite sua justificativa" %>

  <%= f.submit 'Confirmar', id: "button-submit-new-justification-approve" %>
<% end %>

app/views/spaces/_form.html.erb
<%= stylesheet_link_tag ('space') %>
<%= form_with(model: @space, id: "space_form", data: { turbo_frame: "_top" }) do |f| %>
  <!-- Exibe mensagens de erro -->
  <!-- <%= render "devise/shared/error_messages", resource: @space %> -->
  
  <%= f.label :name, "Nome:", class: ("required" if @action != 'edit') %>
  <%= error_messages_for_field(@space, :name) %>
  <%= f.text_field :name, id: "nome", placeholder: "Nome" %>

  <%= f.label :location, class: ("required" if @action != 'edit') %>
  <%= error_messages_for_field(@space, :location) %>
  <%= f.text_field :location, id: "localizacao", placeholder: "Localização" %>

  <div class="flex-container">
    <div class="flex-item">
      <%= f.label :capacity, "Capacidade:", class: ("required" if @action != 'edit') %>
      <%= error_messages_for_field(@space, :capacity) %>
      <%= f.number_field :capacity, id: "capacidade", placeholder: "Capacidade" %>
    </div>
    <div class="flex-item">
      <%= f.label :floor, "Andar do espaço:", class: ("required" if @action != 'edit') %>
      <%= error_messages_for_field(@space, :floor) %><br>
      <%= f.radio_button :floor, :ground, id: 'accebilidade-terreo' %> Térreo
      <%= f.radio_button :floor, :first_floor, id: 'accebilidade-1-andar' %> 1º Andar
      <%= f.radio_button :floor, :second_floor, id: 'accebilidade-2-andar' %> 2º Andar
    </div>
  </div>

  <div class="checkbox-group">
    <div>
      <%= f.label :board, "Quadro:", class: ("required" if @action != 'edit') %><br>
      <%= f.radio_button :board, true, id: 'quadro-sim' %> Sim
      <%= f.radio_button :board, false, id: 'quadro-nao' %> Não
    </div>
    <div>
      <%= f.label :laboratory, "Laboratorio:", class: ("required" if @action != 'edit') %><br>
      <%= f.radio_button :laboratory, true, id: 'laboratorio-sim' %> Sim
      <%= f.radio_button :laboratory, false, id: 'laboratorio-nao' %> Não
    </div>
    <div>
      <%= f.label :projector, "Projetor:", class: ("required" if @action != 'edit') %><br>
      <%= f.radio_button :projector, true, id: 'projetor-sim' %> Sim
      <%= f.radio_button :projector, false, id: 'projetor-nao' %> Não
    </div>
    <div>
      <%= f.label :accessibility, "Acessibilidade:", class: ("required" if @action != 'edit') %><br>
      <%= f.radio_button :accessibility, true, id: 'accebilidade-sim' %> Sim
      <%= f.radio_button :accessibility, false, id: 'accebilidade-nao' %> Não
    </div>
  </div><br>

  <!-- Botões de ação -->
  <div class="buttons-new">
    <%= link_to 'Voltar', spaces_path, class: "back-new link-back" %>

    <!-- Botão de confirmar -->
    <%= f.submit 'Confirmar', class: "button-submit-new" %>
  </div>
<% end %>

app/views/spaces/_history.html.erb
<%= form_with url: reservation_history_space_path(@space, format: :pdf), method: :get, html: { target: "_blank" }, remote: true do |f| %>
  <!-- Campo de data inicial -->
  <div>
    <%= f.label :start_date, "Data Inicial:", id: "label-start-date-pdf" %>
    <%= f.date_field :start_date, id: "start-date-pdf", placeholder: "dd/mm/aaaa", value: params[:start_date] %>
  </div>

  <!-- Campo de data final -->
  <div>
    <%= f.label :end_date, "Data Final:", id: "label-end-date-pdf" %>
    <%= f.date_field :end_date, id: "end-date-pdf", placeholder: "dd/mm/aaaa", value: params[:end_date] %>
  </div>

  <%= f.submit "Gerar PDF", class: "button-pdf" %>
<% end %>

app/views/spaces/_history_filter.html.erb
<%= form_with url: reservation_history_filter_spaces_path(@q, format: :pdf), method: :get, html: { target: "_blank" }, remote: true do |f| %>
<div>
  <%= f.label :start_date, "Data Inicial:", id: "label-start-date-pdf" %>
  <%= f.date_field :start_date, id: "start-date-pdf", placeholder: "dd/mm/aaaa", value: params[:start_date] %>
</div>

<div>
  <%= f.label :end_date, "Data Final:", id: "label-end-date-pdf" %>
  <%= f.date_field :end_date, id: "end-date-pdf", placeholder: "dd/mm/aaaa", value: params[:end_date] %>
</div>

<!-- Campos ocultos para os parâmetros do Ransack -->
<% params[:q]&.each do |key, value| %>
<%= hidden_field_tag "q[#{key}]", value %>
<% end %>

<%= f.submit "Gerar PDF", class: "button-pdf" %>
<% end %>

app/views/spaces/_space_details.html.erb
<div data-controller="menu">
  <%= link_to space_path(space), class: "space-name" do %>
  <div class="details-space-group">
    <h4 id="h4-space"><%= space.name %></h4>
    <span><%= space.location %></span>
    <span>Capacidade: <%= space.capacity %></span>
    <span>Andar: <%= Space.human_enum_name(:floor, :"#{space.floor}") %></span>
    <% if !space.active? %>
      <span>Motivo: <%= space.disabled_reason %></span> 
    <% end %>
  </div>

  <div class="icon-space-group">
    <%= image_tag "icone-projetor", class: "icon-space" if space.projector? %>
    <%= image_tag "icone-acessibilidade", class: "icon-space" if space.accessibility? %>
    <%= image_tag "icone-quadro", class: "icon-space" if space.board? %>
    <%= image_tag "icone-laboratorio", class: "icon-space" if space.laboratory? %>
    <div id="space_icon_occupied_<%= dom_id(space) %>">
      <% if space.occupied? %>
      <%= image_tag "icone-ocupado.png", class: "icon-space" %>
      <% end %>
    </div>
  </div>
  <% end %>

  <% if policy(space).update? %>
  <div class="menu-container">
    <button class="menu-button" data-action="menu#toggle">
      <%= image_tag "icone-menu.png", alt: "Menu Space", size: "27x20" %>
    </button>
    <div class="dropdown-menu" data-menu-target="menu">
      <!-- Botão para alternar o histórico -->
      <% if space.active? %>
        <button class="button-toggle-status" data-action="click->menu#toggleStatus">
          Desabilitar
        </button>
        <div class="filter-options" data-menu-target="toggleStatus" class"hidden">
          <%= render "disable_reason_form", space: space %> <!-- Formulário de motivo para desabilitação -->
        </div>
      <% else %>
      <%= render "toggle_status_button_active", space: space %>
      <% end %>
      <%= render "toggle_occupied_button", space: space %>
      <%= link_to "Editar", edit_space_path(space), data: { turbo_frame: "modal" }, class: "dropdown-item" %>
      <%= link_to "Excluir", space_path(space), data: { turbo_confirm: 'Tem certeza que deseja deletar?', turbo_method: :delete }, class: "dropdown-item delete-item" %>
    </div>
  </div>
  <% end %>
</div>

app/views/spaces/_toggle_occupied_button.html.erb
<%= content_tag(:div, id: "toggle_occupied_button_#{dom_id(space)}") do %>
<% space_status_label = space.occupied ? "Desocupar" : "Ocupar" %>
<%= button_to space_status_label, toggle_occupied_space_path(space), class: "button-toggle-status" %>
<% end %>

app/views/spaces/_toggle_status_button_active.html.erb
<%= content_tag(:div, id: "toggle_status_button_active#{dom_id(space)}") do %>
  <%= button_to "Habilitar", toggle_status_active_space_path(space), class: "button-toggle-status" %>
<% end %>

app/views/spaces/disable_reason.html.erb
<%= render TurboModalComponent.new(title: "Justificativa para desabilitar") do |component| %>
  <% component.with_body do %>
    <%= render "disable_reason_form", resource: @space %>
  <% end %>
<% end %>

app/views/spaces/edit.html.erb
<%= render TurboModalComponent.new(title: "Editar Espaço") do |component| %>
  <% component.with_body do %>
    <%= render "form", resource: @space %>
  <% end %>
<% end %>

app/views/spaces/index.html.erb
<%= stylesheet_link_tag('space')%>

<body>
  <div class="container-space">
    <!-- Barra de pesquisa com filtros -->
    <div class="search-bar" data-controller="filter">
      <%= search_form_for @q, url: spaces_path, method: :get, remote: true, class: "search-form" do |f| %>
      <%= f.text_field :name_i_cont, placeholder: "Pesquisar espaços...", id: "search-input", class: "search-input", autocomplete: "off" %>

      <div class="icons-container">
        <input type="checkbox" id="filterToggle" class="filter-checkbox" style="display:none;" data-filter-target="filterToggle">
        <label for="filterToggle" class="filter-btn" data-action="click->filter#toggle">
          <%= image_tag "filtro.png", alt: "Filtro" %>
        </label>

        <!-- Botão submit que dispara a pesquisa ao clicar na lupa -->
        <button type="submit" class="search-btn">
          <%= image_tag "lupa.png", alt: "Pesquisar" %>
        </button>

        <% if current_user.admin? %>
        <input type="checkbox" id="historyToggle" class="history-checkbox" style="display:none;" data-filter-target="historyToggle">
        <label for="historyToggle" class="history-btn" data-action="click->filter#toggleHistoryFilter">
          <%= image_tag "icone-impressora.png", alt: "Imprimir Histórico" %>
        </label>
        <% end %>
      </div>

      <!-- Filtros -->
      <div class="filters" data-filter-target="filters">
        <div class="profile-header">
          <h4>Filtro de Pesquisa</h4>
        </div>

        <label>Capacidade mínima:
          <%= f.number_field :capacity_gteq, id: "number-search", autocomplete: "off" %>
        </label>
        <label>Capacidade máxima:
          <%= f.number_field :capacity_lteq, id: "number-search", autocomplete: "off" %>
        </label>
        <label>Quadro?
          <%= f.radio_button :board_eq, true, checked: false %> Sim
          <%= f.radio_button :board_eq, false, checked: false %> Não
        </label>
        <label>Projetor ?
          <%= f.radio_button :projector_eq, true, checked: false %> Sim
          <%= f.radio_button :projector_eq, false, checked: false %> Não
        </label>
        <label>Laboratório ?
          <%= f.radio_button :laboratory_eq, true, checked: false %> Sim
          <%= f.radio_button :laboratory_eq, false, checked: false%> Não
        </label>
        <label>Para PCDs ?
          <%= f.radio_button :accessibility_eq, true, checked: false %> Sim
          <%= f.radio_button :accessibility_eq, false, checked: false%> Não
        </label>

        <div class="button-container-space">
          <%= f.submit 'Aplicar Filtros', class: "submit-tag" %>
        </div>
        <% end %>
      </div>
      <div class="history-filter-options" data-filter-target="historyFilterOptions" style="display: none;">
        <%= render "history_filter" %>
      </div>
    </div>

    <div class="spaces-grid">
      <% if @spaces.any? %>
      <% @spaces.each do |space| %>
      <!-- Bloco do espaço com a classe space-item -->
      <div class="space-item <%= 'disabled' if !space.active? %>" id="space_item_<%= dom_id(space) %>">
        <%= render partial: "space_details", locals: { space: space } %>
      </div>
      <% end %>
      <% else %>
      <p><%= !@q.result.present? ? "Nenhum resultado encontrado para sua busca." : "Nenhum espaço cadastrado ainda" %></p><br>
      <p></p><br>
      <% if current_user.admin? && !@any_spaces_exist %>
      <%= link_to "Cadastrar Espaço", new_space_path, data: { turbo_frame: "modal" } %>
      <% end %>
      <% end %>
    </div>
  </div>
</body>

app/views/spaces/new.html.erb
<%= render TurboModalComponent.new(title: "Cadastrar Espaço") do |component| %>
  <% component.with_body do %>
    <%= render "form", resource: @space %>
  <% end %>
<% end %>

app/views/spaces/reservation_history_filter.pdf.erb
<body class="body-pdf">
  <div class="chapter budget">
    <% if @reservations_history_filter.any? %>
      <% current_space = nil %>
        <% @reservations_history_filter.each do |reservation| %>
          <% if current_space != reservation.space.name %>
            <% current_space = reservation.space.name %>
            <div class="page-break"></div>
            <div id="header-pdf"> 
              <h1>Histórico de reservas <%= current_space %></h1>
            </div> 
            <table>
              <thead>
                <tr>
                  <th>Reservante</th>
                  <th>Informação da Reserva</th>
                  <th>Data de Início</th>
                  <th>Data de Fim</th>
                  <th>Turno</th>
                </tr>
              </thead>
            <tbody>
          <% end %>
                <tr>
                  <td><%= reservation.user.name %></td>
                  <td><%= reservation.booking_information %></td>
                  <td><%= reservation.start_date.strftime("%d/%m/%Y") %></td>
                  <td><%= reservation.end_date.strftime("%d/%m/%Y") %></td>
                  <td>
                    <%= Reservation.ordered_shifts.map do |shift|
                      "<div>#{Reservation.translate_shifts([shift]).first}</div>" if reservation.shifts.include?(shift)  
                    end.compact.join.html_safe %>
                  </td>
                </tr>
                <% if @reservations_history_filter.last == reservation || @reservations_history_filter[@reservations_history_filter.index(reservation) + 1].space.name != current_space %>
            </tbody>
          </table>
        <% end %>
      <% end %>
    <% else %>
      <p>Nenhuma reserva encontrada no intervalo selecionado.</p>
    <% end %>
  </div>
</body>

app/views/spaces/toggle_status.turbo_stream.erb
<%= turbo_stream.replace "toggle_status_button_#{dom_id(@space)}" do %>
  <%= render "toggle_status_button", space: @space %>
<% end %>

<%= turbo_stream.replace "space_item_#{dom_id(@space)}" do %>
  <div class="space-item <%= 'disabled' if !@space.active? %>" id="space_item_<%= dom_id(@space) %>">
    <%= render partial: "space_details", locals: { space: @space } %>
  </div>
<% end %>