config/routes.rb
Rails.application.routes.draw do
  mount MissionControl::Jobs::Engine, at: "/jobs"

  root 'spaces#index'

  namespace :searches do
    resources :users, only: [:index]
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :spaces, only: [:index, :show, :new, :create, :edit, :update, :destroy] do 
    member do 
      post :toggle_occupied
      post :toggle_status_active
      post :toggle_status_disable
      get :reservation_history
    end

    collection do
      get :reservation_history_filter
    end
  end
  
  resources :reservations, only: [:new, :create, :edit, :update, :destroy] do 
    collection do
      get :pending_reservation
    end
    member do 
      get :justification_approve
      patch :approve

      get :justification_cancel
      patch :cancel
    end
  end
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :space

  enum status: { pending: 0, confirmed: 1, cancelled: 2 }

  SHIFTS = ["morning", "afternoon", "evening"].freeze

  validates :start_date, presence: true, start_date: { message: 'não pode ser anterior ao dia de hoje' }, on: :create
  validates :end_date, presence: true, end_date: { message: 'não pode ser menor a Data Inicial' }
  validates :shifts, presence: { message: 'O turno não pode ficar em branco' }
  validates :booking_information, presence: true
  validate :validate_unique_shifts, on: :create 

  # Escopos para consultas comuns
  scope :within_date_range, ->(start_date, end_date) { where("start_date <= ? AND end_date >= ?", end_date, start_date) if start_date.present? && end_date.present? }
  scope :for_space, ->(space_id) { where(space_id: space_id) }
  scope :by_user, ->(user_id) { where(user_id: user_id) }
  scope :other_users, ->(user_id) { where.not(user_id: user_id) }
  scope :with_shifts, ->(shifts) { where("shifts && ARRAY[?]::varchar[]", shifts) } # Verifica a interseção dos turnos
  scope :by_date_range, ->(start_date, end_date) {
  where("start_date <= ? AND end_date >= ? AND status = ?", end_date, start_date, Reservation.statuses[:confirmed]) if start_date.present? && end_date.present? } # para listar o histórico de reservas

  def self.translate_shifts(shifts)
    shifts.map { |shift| I18n.t("activerecord.attributes.reservation.shifts.#{shift}") }
  end

  def self.conflicting_shifts(existing_reservations, new_shifts)
    existing_reservations.map(&:shifts).flatten & new_shifts
  end

  # Método para adicionar turnos a uma reserva existente, garantindo que não haja duplicatas
  def self.add_shifts(existing_reservation, new_shifts)
    (existing_reservation.shifts + new_shifts).uniq
  end

  # método para renderizar data no simple calendar
  def start_time
    self.start_date
  end

  def end_time
    self.end_date
  end

  def self.ordered_shifts
    SHIFTS
  end

  private 
    def validate_unique_shifts
      overlapping_reservations = Reservation.where(
      space_id: space_id)
      .where("start_date <= ? AND end_date >= ?", end_date, start_date)
      .where("shifts && ARRAY[?]::varchar[]", shifts)

      if overlapping_reservations.exists?
        errors.add(:shifts, "O turno(s) selecionado(s) já foi reservado para essa data")
      end
    end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: %i[edit update destroy justification_approve justification_cancel approve cancel]
  before_action :set_action, only: %i[edit update]
  after_action :verify_authorized, only: [:approve, :cancel]

  def new 
    start_date = params[:start_date]
    end_date = params[:end_date]
    @reservation = Reservation.new(start_date: start_date, end_date: end_date)  
  end

  def create
    new_shifts = reservation_params[:shifts] || []
    new_start_date = reservation_params[:start_date]
    new_end_date = reservation_params[:end_date]

    # Busque reservas existentes para o mesmo espaço dentro do intervalo de datas
    existing_reservations = Reservation
                                      .for_space(reservation_params[:space_id])
                                      .within_date_range(new_start_date, new_end_date)
                                      .by_user(current_user.id)

    if existing_reservations.exists? && new_start_date.present? && new_end_date.present? && new_shifts.present?
      existing_reservation = existing_reservations.first
      
      # Verifique se as datas da nova reserva são exatamente iguais à reserva existente
      if existing_reservation.start_date == new_start_date && existing_reservation.end_date == new_end_date
        # Se as datas coincidirem, verifique o conflito de turnos
        conflicting_shifts = Reservation.conflicting_shifts([existing_reservation], new_shifts)

        if conflicting_shifts.any?
          flash[:alert] = "Os turnos já foram reservados: #{Reservation.translate_shifts(conflicting_shifts).join(', ')}"
          redirect_to space_path(existing_reservation.space)
        else
          # Adicione novos turnos à reserva existente
          updated_shifts = Reservation.add_shifts(existing_reservation, new_shifts)

          if existing_reservation.update(shifts: updated_shifts)
            flash[:notice] = "Reserva atualizada com sucesso!"
            redirect_to space_path(existing_reservation.space)
          else
            respond_to do |format|
              format.turbo_stream
            end
          end
        end
      else
        # Se as datas forem diferentes, crie uma nova reserva
        @reservation = Reservation.new(reservation_params)
        @reservation.user = current_user unless reservation_params[:user_id].present? 

        if @reservation.save
          if current_user.admin? 
            @reservation.update(status: "confirmed")
            flash[:notice] = "Reserva realizada com sucesso!"
            redirect_to space_path(@reservation)
          else
            flash[:notice] = "Reserva solicitada com sucesso!"
            redirect_to space_path(@reservation)
            NotifyAdminJob.perform_later(User.admins.first)
          end
        else
          respond_to do |format|
            format.turbo_stream
          end
        end
      end
    else
      # Caso não exista reserva no intervalo de datas, crie uma nova reserva
      @reservation = Reservation.new(reservation_params)
      @reservation.user = current_user unless reservation_params[:user_id].present? 

      if @reservation.save
        if current_user.admin? 
          @reservation.update(status: "confirmed")
          flash[:notice] = "Reserva realizada com sucesso!"
          redirect_to space_path(@reservation)
          NotifyUserReservationJob.perform_later(@reservation.user)
        else
          flash[:notice] = "Reserva solicitada com sucesso!"
          redirect_to space_path(@reservation)
          NotifyAdminJob.perform_later(User.admins.first)
        end
      else
        respond_to do |format|
          format.turbo_stream
        end
      end
    end
  end

  def edit; end 

  def update
    authorize @reservation

    new_shifts = reservation_params[:shifts] || []
    new_start_date = reservation_params[:start_date]
    new_end_date = reservation_params[:end_date]

    # Buscar reservas conflitantes no mesmo espaço e no intervalo de datas (excluindo a reserva atual)
    conflicting_reservations = Reservation
                              .within_date_range(new_start_date, new_end_date)
                              .for_space(@reservation.space_id)
                              .where.not(id: @reservation.id)

    # Verificar se há turnos conflitantes com outras reservas para o intervalo de datas
    conflicting_shifts = Reservation.conflicting_shifts(conflicting_reservations, new_shifts)
    conflicting_shifts_translated = Reservation.translate_shifts(conflicting_shifts)

    # Impedir a atualização se houver conflito, seja usuário comum ou admin
    if conflicting_shifts.any?
      flash[:alert] = "O turno #{conflicting_shifts_translated.join(', ')} já foi reservado para essas datas por outro usuário."
      redirect_to space_path(@reservation)
    else
      # Caso não haja conflito, procedemos com a atualização
      if update_reservation(new_start_date, new_end_date, new_shifts, conflicting_reservations)
        if current_user.admin?
          flash[:notice] = "Reserva atualizada com sucesso!"
          redirect_to space_path(@reservation)
          NotifyUpdateReservationUserJob.perform_later(@reservation.user)
        else
          @reservation.update(status: "pending")          
          flash[:notice] = "Reserva solicitada com sucesso!"
          redirect_to space_path(@reservation)
          NotifyAdminJob.perform_later(User.admins.first)
        end
      else
        flash[:alert] = "Erro ao atualizar a reserva."
        respond_to do |format|
          format.turbo_stream
        end
      end
    end
  end

  def destroy
    authorize @reservation
    @reservation.destroy!
    flash[:notice] = "Reserva excuída com sucesso!"
    redirect_to space_path(@reservation)
    unless current_user.admin?
      NotifyAdminDestroyReservationJob.perform_later(User.admins.first)
    else
      NotifyUserDestroyReservationJob.perform_later(@reservation.user)
    end
  end

  def pending_reservation 
    @pending_reservations = Reservation.where(status: 0).order(:start_date) 
    if @pending_reservations.empty?
      flash[:notice] = "Você não possui nenhuma reserva pendente!"
      redirect_to spaces_path
    end
  end

  def justication_approve; end

  def approve
    authorize @reservation, :approve?

    justification = params[:justification]

    if @reservation.update(status: :confirmed)
      flash[:notice] = "Reserva aprovada com sucesso."
      redirect_to pending_reservation_reservations_path
      NotifyApproveReservationUserJob.perform_later(@reservation.user, justification)
    else
      flash.now[:alert] = "Não foi possível aprovar a reserva."
    end
  end

  def justication_cancel; end

  def cancel
    authorize @reservation, :cancel? 

    justification = params[:justification]

    if @reservation.destroy
      NotifyCancelReservationUserJob.perform_later(@reservation.user, justification)
      @reservation.destroy
      redirect_to pending_reservation_reservations_path
      flash[:notice] = "Reserva cancelada e removida com sucesso."
    else
      flash.now[:alert] = "Não foi possível cancelar a reserva."
    end
  end

  private
    def update_reservation(new_start_date, new_end_date, new_shifts, existing_reservations)
      if existing_reservations.by_user(current_user.id).exists?
        existing_reservation = existing_reservations.by_user(current_user.id).first
        updated_shifts = Reservation.add_shifts(existing_reservation, new_shifts)
        return existing_reservation.update(start_date: new_start_date, end_date: new_end_date, shifts: updated_shifts)
      else
        @reservation.update(start_date: new_start_date, end_date: new_end_date, shifts: new_shifts)
      end
    end

    def reservation_params 
      params.require(:reservation).permit(:start_date, :end_date, :space_id, :user_id, :description, :booking_information, :justification, shifts: [])
    end

    def set_reservation 
      @reservation = Reservation.find(params[:id])
    end

    def set_action
      @action = 'edit'
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= stylesheet_link_tag('reservation') %>
<%= form_with(model: @reservation, id: "reservation_form", data: { turbo_frame: "_top" }) do |f| %>

<!-- Exibe mensagens de erro -->
<!-- <%= render "devise/shared/error_messages", resource: @reservation %> -->
<div class="flex-container">
  <!-- Campo de data da reserva -->
  <div class="flex-item-reservation">
    <%= f.label :start_date, "Data Inicial:", class: ("required" if @action != 'edit') %>
    <%= error_messages_for_field(@reservation, :start_date) %>
    <%= f.date_field :start_date, id: "reservation-start-date", placeholder: "dd/mm/aaaa" %>
  </div>
  <div class="flex-item-reservation">
    <%= f.label :end_date, "Data Final:", class: ("required" if @action != 'edit') %>
    <%= error_messages_for_field(@reservation, :end_date) %>
    <%= f.date_field :end_date, id: "reservation-end-date", placeholder: "dd/mm/aaaa" %>
  </div>
</div>

<%= f.label :booking_information, "Motivo da reserva:", class: ("required" if @action != 'edit') %>
<%= error_messages_for_field(@reservation, :booking_information) %>
<%= f.text_field :booking_information, id: "booking-information", placeholder: "Digite o motivo da reserva" %>

<%= f.label :description, "Descrição:" %>
<%= error_messages_for_field(@reservation, :description) %>
<%= f.text_field :description, id: "booking-information", placeholder: "Digite uma descrição se necessário" %>

<!-- Grupo de checkboxes para os turnos -->
<div class="checkbox-group">
  <%= f.label :shifts, "Selecione o tuno:", class: ("required" if @action != 'edit') %>
  <%= error_messages_for_field(@reservation, :shifts) %>

  <div>
    <%= f.check_box :shifts, { multiple: true }, "morning", nil %>
    <%= f.label :shift_morning, "Manhã" %>
  </div>
  <div>
    <%= f.check_box :shifts, { multiple: true }, "afternoon", nil %>
    <%= f.label :shift_afternoon, "Tarde" %>
  </div>
  <div>
    <%= f.check_box :shifts, { multiple: true }, "evening", nil %>
    <%= f.label :shift_evening, "Noite" %>
  </div>
</div>

<% if current_user.admin? %>
  <div class="combobox-container">
    <%= f.combobox :user_id, searches_users_path, label: "Usuário", placeholder: "Selecione o usuário:" if @action != 'edit'%>
  </div>
<% end %>

<% if @action == 'edit' %>
<%= f.label :name, "Nome do Reservante:", class: ("required" if @action != 'edit') %>
<p id="p-reservation-name"><%= @reservation.user.name %></p>
<p id="p-reservation-name"><%= @reservation.user.email %></p>
<p id="p-reservation"><%= @reservation.user.formatted_phone_number %></p>
<% end %>

<!-- Campo oculto para o id do espaço -->
<%= f.hidden_field :space_id, value: session[:last_space_id] %>

<!-- Botões de ação -->
<div class="buttons-new">
  <%= link_to 'Voltar', request.referrer || space_path(session[:last_space_id]), class: "back-new link-back" %>
  <!-- <%= link_to 'Voltar', request.referrer, class: "back-new link-back" %> -->

  <% if @action == 'edit' %>
  <%= link_to 'Excluir reserva', reservation_path(@reservation), data: { turbo_confirm: 'Tem certeza que deseja deletar?', turbo_method: :delete }, class: "back-delete link-back" %>
  <% end %>

  <!-- Botão de confirmar -->
  <%= f.submit 'Confirmar', class: "button-submit-new" %>
</div>
<% end %>

app/views/reservations/_justification_approve_form.html.erb
<%= form_with url: approve_reservation_path(@reservation), method: :patch, id: "justification_approve_form" do |f| %>
  <%= f.label :justification, "Informações adicionais ao reservante:" %>
  <%= error_messages_for_field(@reservation, :justification) %>
  <%= f.text_area :justification, rows: 4, id: "rejection-reason", placeholder: "Ex: Onde buscar a chave" %>

  <%= f.submit 'Confirmar', id: "button-submit-new-justification-approve" %>
<% end %>

app/views/reservations/_justification_cancel_form.html.erb
<%= form_with url: cancel_reservation_path(@reservation), method: :patch, id: "justification_cancel_form" do |f| %>
  <%= f.label :justification, "Informe o motivo da rejeição:" %>
  <%= error_messages_for_field(@reservation, :justification) %>
  <%= f.text_area :justification, rows: 4, id: "rejection-reason", placeholder: "Digite o motivo da rejeição da reserva" %>

  <%= f.submit 'Confirmar', id: "button-submit-new-justification-cancel" %>
<% end %>

app/views/reservations/_pending.html.erb
<%= turbo_frame_tag dom_id(reservation) do %>  
  <div class="pending-list">
    <div class="pending-row header">
      <div class="pending-column pending">Reservante</div>
      <div class="pending-column pending">Espaço</div>
      <div class="pending-column pending">Descrição</div>
      <div class="pending-column start-date">Data Inicial</div>
      <div class="pending-column end-date">Data Final</div>
      <div class="pending-column booking-information">Motivo da reserva</div>
      <div class="pending-column status">Status</div>
      <div class="pending-column actions"></div>
    </div>
    
    <div class="pending-row">
      <div class="pending-column pending">
        <div class="pending-info">
          <p class="name"><%= reservation.user.name %></p>
          <p class="email"><%= reservation.user.email %></p>
        </div>
      </div>
      <div class="pending-column pending"><%= reservation.space.name %></div>
      <div class="pending-column pending"><%= reservation.description %></div>
      <div class="pending-column start-date"><%= reservation.start_date.strftime("%d/%m/%Y") %></div>
      <div class="pending-column end-date"><%= reservation.end_date.strftime("%d/%m/%Y") %></div>
      <div class="pending-column booking-information"><%= reservation.booking_information %></div>
      <div class="pending-column status"><span class="status-label inactive"><%= Reservation.human_enum_name(:status, :"#{reservation.status}") %></span></div>
      <div class="pending-column actions">
        <%= button_to justification_approve_reservation_path(reservation), method: :get, data: { turbo_frame: "modal" }, class: "bt edit" do %>
          <%= image_tag "icone-confirma", size: "25x25" %>
        <% end %>
        <%= button_to justification_cancel_reservation_path(reservation), method: :get, data: { turbo_frame: "modal" }, class: "bt delete" do %>
          <%= image_tag "icone-cancelar", size: "25x25", class: "icone-cancel" %>
        <% end %>
      </div>
    </div>   
  </div><br>
<% end %>

app/views/reservations/approve.turbo_stream.erb
<%= turbo_stream.remove dom_id(@reservation) do %>
  <%= render "pending", reservation: @reservation %>
<% end %>

<%= turbo_stream.update "flash" do %>
  <%= render "layouts/flash" %>
<% end %>

app/views/reservations/cancel.turbo_stream.erb
<%= turbo_stream.remove dom_id(@reservation) do %>
  <%= render "pending", reservation: @reservation %>
<% end %>

<%= turbo_stream.update "flash" do %>
  <%= render "layouts/flash" %>
<% end %>

app/views/reservations/create.turbo_stream.erb
<%= turbo_stream.replace("reservation_form", partial: "reservations/form", locals: { reservation: @reservation }) %>

app/views/reservations/edit.html.erb
<%= render TurboModalComponent.new(title: "Editar Reserva") do |component| %>
  <% component.with_body do %>
    <%= render "form", resource: @reservation %>
  <% end %>
<% end %>

app/views/reservations/justification_approve.html.erb
<%= render TurboModalComponent.new(title: "Justificar rejeição da Reserva") do |component| %>
  <% component.with_body do %>
    <%= render "justification_approve_form", resource: @reservation %>
  <% end %>
<% end %>

app/views/reservations/justification_cancel.html.erb
<%= render TurboModalComponent.new(title: "Justificar rejeição da Reserva") do |component| %>
  <% component.with_body do %>
    <%= render "justification_cancel_form", resource: @reservation %>
  <% end %>
<% end %>

app/views/reservations/new.html.erb
<%= render TurboModalComponent.new(title: "Realize sua Reserva") do |component| %>
  <% component.with_body do %>
    <%= render "form", resource: @reservation %>
  <% end %>
<% end %>

app/views/reservations/pending_reservation.html.erb
<% @pending_reservations.each do |reservation| %>
  <%= render "pending", reservation: reservation %>
<% end %>

app/views/reservations/update.turbo_stream.erb
<%= turbo_stream.replace("reservation_form", partial: "reservations/form", locals: { reservation: @reservation }) %>