config/routes.rb
Rails.application.routes.draw do
  mount MissionControl::Jobs::Engine, at: "/jobs"

  root 'spaces#index'

  namespace :searches do
    resources :users, only: [:index]
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :spaces, only: [:index, :show, :new, :create, :edit, :update, :destroy] do 
    member do 
      post :toggle_occupied
      post :toggle_status_active
      post :toggle_status_disable
      get :reservation_history
    end

    collection do
      get :reservation_history_filter
    end
  end
  
  resources :reservations, only: [:new, :create, :edit, :update, :destroy] do 
    collection do
      get :pending_reservation
    end
    member do 
      get :justification_approve
      patch :approve

      get :justification_cancel
      patch :cancel
    end
  end
end

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>

    <nav>
      <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
      <%= link_to t('simple_calendar.today', default: 'Today'), calendar.url_for_today_view %>
      <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
    </nav>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% instance_exec(day, calendar.sorted_events_for(day), &passed_block) %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <nav>
      <div class="calendar-navigation">
        <%= link_to (image_tag('icone-seta-esquerda.png', size: "50x36")), calendar.url_for_previous_view %>

        <time datetime="<%= start_date.strftime('%Y-%m') %>" class="calendar-title">
          <%= t('date.month_names')[start_date.month] %> <%= start_date.year %>
        </time>

        <%= link_to (image_tag('icone-seta-direita.png', size: "50x36")), calendar.url_for_next_view %>
      </div>

      <div>
        <h2 class="calendar-header">Calendário de Reservas - <%= @space.name %></h2>
        <span>Capacidade: <%= @space.capacity %></span><br>
        <span>Localização: <%= @space.location %></span><br>
        <span>Andar: <%= Space.human_enum_name(:floor, :"#{@space.floor}") %></span>
      </div>

      <div class="calendar-buttons">
        <%= link_to new_reservation_path, data: { turbo_frame: "modal" }, class: 'button-reserve' do %>
        Realizar reserva <%= image_tag('icone-botao-mais.png', class: 'icon-plus') %>
        <% end %>

        <%= link_to t('simple_calendar.today', default: 'Hoje'), calendar.url_for_today_view, class: 'button-today' %>

        <% if current_user.admin? %>
        <div data-controller="history">
          <!-- Botão para abrir o filtro de histórico -->
          <button class="button-reserve" type="button" data-action="history#toggle" class="filter-button">
            Gerar Histórico
          </button>

          <!-- Opções de filtro de histórico (inicialmente ocultas) -->
          <div data-history-target="historicalFilters" class="filter-options">
            <%= render "history" %>
          </div>
        </div>
        <% end %>
      </div>
    </nav>
  </div>


  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
        <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
      <tr>
        <% week.each do |day| %>
        <%= content_tag :td, class: calendar.td_classes_for(day) do %>
        <% instance_exec(day, calendar.sorted_events_for(day), &passed_block) %>
        <% end %>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to spaces_path do %>
  <%= image_tag "icone-voltar", alt: "Icone de voltar", class: "icone-back-calendar" %>
  <% end %>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <span class="calendar-title">
      <%= t('simple_calendar.week', default: 'Week') %>
      <%= calendar.week_number %>
      <% if calendar.number_of_weeks > 1 %>
        - <%= calendar.end_week %>
      <% end %>
    </span>

    <nav>
      <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
      <%= link_to t('simple_calendar.today', default: 'Today'), calendar.url_for_today_view %>
      <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
    </nav>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% instance_exec(day, calendar.sorted_events_for(day), &passed_block) %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>