config/routes.rb
Rails.application.routes.draw do
  mount MissionControl::Jobs::Engine, at: "/jobs"

  root 'spaces#index'

  namespace :searches do
    resources :users, only: [:index]
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :spaces, only: [:index, :show, :new, :create, :edit, :update, :destroy] do 
    member do 
      post :toggle_occupied
      post :toggle_status_active
      post :toggle_status_disable
      get :reservation_history
    end

    collection do
      get :reservation_history_filter
    end
  end
  
  resources :reservations, only: [:new, :create, :edit, :update, :destroy] do 
    collection do
      get :pending_reservation
    end
    member do 
      get :justification_approve
      patch :approve

      get :justification_cancel
      patch :cancel
    end
  end
end

app/views/layouts/_flash.html.erb
<%= turbo_frame_tag "flash" do %>
  <% if notice %>
    <div data-controller="flash" data-flash-text-value="<%= notice %>" data-flash-type-value="success"></div>
  <% end %>
  <% if alert %>
    <div data-controller="flash" data-flash-text-value="<%= alert %>" data-flash-type-value="error"></div>
  <% end %>
<% end %>

app/views/layouts/_topnavbar.html.erb
<header>
  <div class="logo-container">
    <%= image_tag "ufpa-logo.png", alt: "UFPA Logo", class: "logo" %>
  </div>

  <% if action_name == "index" && current_user.admin? %>
  <%= link_to "Reservas pendentes", pending_reservation_reservations_path, data: { turbo_stream: true }, class: "button-space" %>
  <% end %>

  <% if action_name == "pending_reservation" || action_name == "show"%>
  <%= link_to "Voltar aos espaços", spaces_path, class: "button-space" %>
  <% end %>

  <div class="profile-container" data-controller="profile-menu">
    <input type="checkbox" id="profileToggle" data-target="profile-menu.checkbox">
    <label for="profileToggle" data-action="click->profile-menu#toggleMenu">
      <%= image_tag "icone-menu.png", alt: "Menu de Perfil" %>
    </label>
    <div class="profile-card" data-profile-menu-target="menu">
      <div class="profile-header">
        <% if user_signed_in? %>
        <h3><%= current_user.name %></h3>
        <p><%= current_user.email %></p>
        <% end %>
      </div>
      <ul>
        <li><%= link_to "Espaços", spaces_path %></li>
        <% if current_user && current_user.admin? %>
        <li><%= link_to "Cadastrar Espaço", new_space_path, data: { turbo_frame: "modal" } %></li>
        <% end %>
        <% if current_user && current_user.admin? %>
        <li><%= link_to "Cadastrar Usuário", new_user_registration_path %></li>
        <% end %>
        <% if action_name == "show"%>
        <!-- Switch para Minhas Reservas -->
        <li>
          <div class="switch-container" data-controller="reservation">
            <span id="span-name">Minhas Reservas</span>
            <label class="switch">
              <%= check_box_tag 'my_reservations', '1', params[:my_reservations].present?, id: 'myReservationsSwitch', data: { action: "change->reservation#toggleFilter" } %>
              <span class="slider"></span>
            </label>
          </div>
        </li>
        <% end %>
        <li><%= link_to "Editar Perfil", edit_user_registration_path, data: { turbo_frame: "modal" } %></li>
        <li><%= link_to "Sair", destroy_user_session_path, data: { turbo_method: :delete } %></li>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpaceMarking</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!-- <meta name="turbo-refresh-method" content="morph"> -->
    <meta name="turbo-refresh-scroll" content="preserve">
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "devise", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "reservation", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "simple_calendar", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "space", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "turbo_modal", "data-turbo-track": "reload" %>
    <%= combobox_style_tag %>

    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module", defer: true %>
  </head>

  <body>
    <% unless devise_controller? && (controller_name == 'registrations' || controller_name == 'confirmations' || controller_name == 'sessions' || controller_name == 'passwords' || controller_name == 'users') %>
      <%= render "layouts/topnavbar" %>
    <% end %>
    
    <%= render "layouts/flash" %>

    <%= yield %>

    <%= turbo_frame_tag "modal", target: "_top" %>
  </body>
</html>

app/views/layouts/create.turbo_stream.erb
<%= turbo_stream.update 'flash', partial: 'layouts/flash' %>

app/views/layouts/pdf.pdf.erb
<!doctype html>
<html>
  <head>
    <meta charset='utf-8' />
    <%= wicked_pdf_stylesheet_link_tag "pdf" -%>
    <%= wicked_pdf_javascript_include_tag "number_pages" %>
  </head>
  
  <body onload='number_pages'>
    <!-- <div id="header"> -->
      <!-- <%= wicked_pdf_image_tag 'mysite.jpg' %> -->
     <!--</div> -->
    <div id="content">
      <%= yield %>
    </div>
  </body>
  <footer class="footer-pdf">
    <hr/>
    <span><a class="a-pdf" href="reservaespaco@email.com">reservaespaco@email.com</a> | <a class="a-pdf" href="https://ufpa.br">ufpa.br</a></span>
  </footer> 
</html>